# config/data_locations.yml
# -------------------------------------------------------------------------
# Additional ArcGIS / external data sources per project.
# These will be automatically added to `make_project_data_locations()` results.
#
# Keys:
#   label:      Display name with short description of the data
#   url:        Direct REST or web URL (optional if using 'use_attr')
#   aoifilter:  true/false — whether to apply AOI spatial filter (default: true)
#   insert_at:  Optional integer index for insertion in the list
#   priority:   Display or load priority (lower = project-specific, higher = global)
# -------------------------------------------------------------------------

additional_data_locations:
  default:
    # --- National context layers ---
    - label: "Roads - Cardiff National road and street network to be used as the source of road datasets."
      url: "https://services-eu1.arcgis.com/8uHkpVrXUjYCyrO4/arcgis/rest/services/CC_Roads_Fill/FeatureServer/0" 
      aoifilter: true
      priority: 100

   # - label: "Buildings - National building footprints dataset representing structures and property outlines."
  #    url: "https://services.arcgis.com/qHLhLQrcvEnxjtPr/arcgis/rest/services/OS_OpenMap_Local_Buildings/FeatureServer/0"
 #     aoifilter: true
#      priority: 100

   # - label: "Green Spaces - National layer representing parks, recreational areas, and public open spaces."
  #    url: "https://services.arcgis.com/qHLhLQrcvEnxjtPr/arcgis/rest/services/OS_Open_Greenspace/FeatureServer/1"
 #     aoifilter: true
#      priority: 100
  
  # --- Project-specific layers ---
  CC_Cardiff_07102025:
    - label: "Tree Points - Individual tree point dataset representing surveyed tree locations, species and health data across Cardiff."
      url: "https://services-eu1.arcgis.com/8uHkpVrXUjYCyrO4/arcgis/rest/services/ArbotrackPoints_CC_07102025/FeatureServer/0"
      aoifilter: true
      priority: 10

#    - label: "Tree Polygons -Tree Crowns with Species and Health Information - Tree Crown data with Ash and other Species data along with their health levels and health information from counsel data."
#      url: "https://services-eu1.arcgis.com/8uHkpVrXUjYCyrO4/arcgis/rest/services/ArbotrackPolygons_CC_07102025/FeatureServer/0"
#      aoifilter: true
#      priority: 10

  #  - label: "Open Space - Layer representing Cardiff’s parks, gardens, and accessible public green areas."
  #    url: "https://services-eu1.arcgis.com/8uHkpVrXUjYCyrO4/arcgis/rest/services/OpenSpaces_CC_2025/FeatureServer/0"
  #    aoifilter: true
  #    priority: 10 
    
 #   - label: "Building - Cardiff’s local building footprint dataset representing property outlines for analysis."
 #     url: "https://services-eu1.arcgis.com/8uHkpVrXUjYCyrO4/arcgis/rest/services/Building_CC_01102025/FeatureServer/0"
 #     aoifilter: true
 #     priority: 10 

   # - label: "Non Operational Property - Cardiff Council properties not in operational use, included for ownership context."
    #  url: "https://services-eu1.arcgis.com/8uHkpVrXUjYCyrO4/arcgis/rest/services/NonOperationalProperty_CC_2025/FeatureServer/0"
    #  aoifilter: true
    #  priority: 10

   # - label: "Operational Property - Cardiff Council operational property boundaries used for management and analysis."
      #url: "https://services-eu1.arcgis.com/8uHkpVrXUjYCyrO4/arcgis/rest/services/OperationalProperty_CC_2025/FeatureServer"
     # aoifilter: true
    #  priority: 10

#    - label: "Tree Crowns with Species and Health Information - Tree Crown data with Ash and other Species data along with their health levels and health information surveyed by Vertinetik."
#      url: "https://services-eu1.arcgis.com/8uHkpVrXUjYCyrO4/arcgis/rest/services/TreeCrowns_CC_CardiffTrials_5cm_2026/FeatureServer/0"
#     aoifilter: true
#      priority: 10

    - label: "TMA Risk Layer - Layer created by TMA showing various risk areas in Cardiff City."
      url: "https://services-eu1.arcgis.com/8uHkpVrXUjYCyrO4/arcgis/rest/services/TMA_CC_Enviromap_Risk_Simplified/FeatureServer/0"
      aoifilter: true  
      priority: 5

 #   - label: "Roads - National road and street network to be used as the source of road datasets."
  #    url: "https://services.arcgis.com/qHLhLQrcvEnxjtPr/arcgis/rest/services/OS_OpenRoads/FeatureServer/1"
  #    aoifilter: true
   #   priority: 5
